# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(909, 290)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.OpenDesktopManager = QtWidgets.QCheckBox(self.centralwidget)
        self.OpenDesktopManager.setObjectName("OpenDesktopManager")
        self.verticalLayout_3.addWidget(self.OpenDesktopManager)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.FileAble = QtWidgets.QCheckBox(self.centralwidget)
        self.FileAble.setObjectName("FileAble")
        self.verticalLayout_2.addWidget(self.FileAble)
        self.FileAuto = QtWidgets.QCheckBox(self.centralwidget)
        self.FileAuto.setObjectName("FileAuto")
        self.verticalLayout_2.addWidget(self.FileAuto)
        self.FileDirInputLabel = QtWidgets.QLabel(self.centralwidget)
        self.FileDirInputLabel.setObjectName("FileDirInputLabel")
        self.verticalLayout_2.addWidget(self.FileDirInputLabel)
        self.FireDirInput = QtWidgets.QLineEdit(self.centralwidget)
        self.FireDirInput.setObjectName("FireDirInput")
        self.verticalLayout_2.addWidget(self.FireDirInput)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.SoftwareAble = QtWidgets.QCheckBox(self.centralwidget)
        self.SoftwareAble.setObjectName("SoftwareAble")
        self.verticalLayout.addWidget(self.SoftwareAble)
        self.SoftwareAuto = QtWidgets.QCheckBox(self.centralwidget)
        self.SoftwareAuto.setObjectName("SoftwareAuto")
        self.verticalLayout.addWidget(self.SoftwareAuto)
        self.SoftwareDirInputLabel = QtWidgets.QLabel(self.centralwidget)
        self.SoftwareDirInputLabel.setObjectName("SoftwareDirInputLabel")
        self.verticalLayout.addWidget(self.SoftwareDirInputLabel)
        self.SoftwareDirInput = QtWidgets.QLineEdit(self.centralwidget)
        self.SoftwareDirInput.setObjectName("SoftwareDirInput")
        self.verticalLayout.addWidget(self.SoftwareDirInput)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.SaveOrCanel = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.SaveOrCanel.setStandardButtons(QtWidgets.QDialogButtonBox.Save)
        self.SaveOrCanel.setObjectName("SaveOrCanel")
        self.verticalLayout_3.addWidget(self.SaveOrCanel)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 909, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.OpenDesktopManager.setText(_translate("MainWindow", "开启整理"))
        self.FileAble.setText(_translate("MainWindow", "启用文件整理"))
        self.FileAuto.setText(_translate("MainWindow", "自动收纳桌面文件"))
        self.FileDirInputLabel.setText(_translate("MainWindow", "文件文件夹名称"))
        self.SoftwareAble.setText(_translate("MainWindow", "启用软件快捷方式整理"))
        self.SoftwareAuto.setText(_translate("MainWindow", "自动收纳桌面快捷方式"))
        self.SoftwareDirInputLabel.setText(_translate("MainWindow", "软件文件夹名称"))
