# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(976, 481)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../Program Files/Internet Explorer/images/bing.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.OpenDesktopManager = QtWidgets.QCheckBox(self.centralwidget)
        self.OpenDesktopManager.setObjectName("OpenDesktopManager")
        self.verticalLayout_3.addWidget(self.OpenDesktopManager)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.FileAble = QtWidgets.QCheckBox(self.centralwidget)
        self.FileAble.setObjectName("FileAble")
        self.verticalLayout_2.addWidget(self.FileAble)
        self.FileAuto = QtWidgets.QCheckBox(self.centralwidget)
        self.FileAuto.setObjectName("FileAuto")
        self.verticalLayout_2.addWidget(self.FileAuto)
        self.FileDirInput = QtWidgets.QLineEdit(self.centralwidget)
        self.FileDirInput.setObjectName("FileDirInput")
        self.verticalLayout_2.addWidget(self.FileDirInput)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.SoftwareAble = QtWidgets.QCheckBox(self.centralwidget)
        self.SoftwareAble.setObjectName("SoftwareAble")
        self.verticalLayout.addWidget(self.SoftwareAble)
        self.SoftwareAuto = QtWidgets.QCheckBox(self.centralwidget)
        self.SoftwareAuto.setObjectName("SoftwareAuto")
        self.verticalLayout.addWidget(self.SoftwareAuto)
        self.SoftwareDirInput = QtWidgets.QLineEdit(self.centralwidget)
        self.SoftwareDirInput.setInputMask("")
        self.SoftwareDirInput.setText("")
        self.SoftwareDirInput.setClearButtonEnabled(False)
        self.SoftwareDirInput.setObjectName("SoftwareDirInput")
        self.verticalLayout.addWidget(self.SoftwareDirInput)
        self.FileClass = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.FileClass.setPlainText("")
        self.FileClass.setObjectName("FileClass")
        self.verticalLayout.addWidget(self.FileClass)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.verticalLayout_3)
        self.SaveOrCanel = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.SaveOrCanel.setStandardButtons(QtWidgets.QDialogButtonBox.Save)
        self.SaveOrCanel.setObjectName("SaveOrCanel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.SaveOrCanel)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 976, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LoshopDesktopManager设置"))
        self.OpenDesktopManager.setText(_translate("MainWindow", "开启整理"))
        self.FileAble.setText(_translate("MainWindow", "启用文件整理"))
        self.FileAuto.setText(_translate("MainWindow", "自动收纳桌面文件"))
        self.FileDirInput.setPlaceholderText(_translate("MainWindow", "文件文件夹名称"))
        self.SoftwareAble.setText(_translate("MainWindow", "启用软件快捷方式整理"))
        self.SoftwareAuto.setText(_translate("MainWindow", "自动收纳桌面快捷方式"))
        self.SoftwareDirInput.setPlaceholderText(_translate("MainWindow", "软件文件夹名称"))
        self.FileClass.setPlaceholderText(_translate("MainWindow", "文件收纳规则"))
